export  const GET_PRODUCTS = 'GET_PRODUCTS'

export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING'
export const GET_PRODUCTS_SUCESS = 'GET_PRODUCTS_SUCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'


export const PRODUCT_DETAILS_PENDING = 'PRODUCT_DETAILS_PENDING'
export const PRODUCT_DETAILS_SUCESS = 'PRODUCT_DETAILS_SUCESS'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'

