export  const GET_PRODUCTS = 'GET_PRODUCTS'

export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING'
export const GET_PRODUCTS_SUCESS = 'GET_PRODUCTS_SUCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'


export const PRODUCT_DETAILS_PENDING = 'PRODUCT_DETAILS_PENDING'
export const PRODUCT_DETAILS_SUCESS = 'PRODUCT_DETAILS_SUCESS'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'


export const  ADD_TO_CART = 'ADD_TO_CART'
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const REMOVE_FROM_CART ='REMOVE_FROM_CART'

export const USER_SIGNIN_PENDING = 'USER_SIGNIN_PENDING'
export const USER_SIGNIN_SUCESS = 'USER_SIGNIN_SUCESS'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'



export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

export const USER_REGISTER_SUCESS = 'USER_REGISTER_SUCESS'

